version: 2

sources:
  - name: bike_production
    database: bikestores_raw_db
    schema: production
    tables:
      - name: brands
        columns:
          - name: brand_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
          - name: brand_name
            description: Brand name of the bike
            tests:
              - unique
              - not null
      - name: categories
      - name: products
      - name: stocks
  - name: bike_sales
    database: bikestores_raw_db
    schema: sales
    tables:
      - name: categories
      - name: customers
      - name: orders
      - name: order_items
      - name: staffs
      - name: stores
