# todo
# 1) create candidate roles, with candidate perms
# 		1A) read-only DAGs, can't execute
# 		1c) read-only DAGs, create & run DAGs)
# 2) test (i.e. assign to a new user)
# 3) validate

# notes
# 1) Every developer should be set/assigned to the Airflow RBAC role 'User'
# 2) Every 'read-only' user should be set/assigned to the Airflow RBAC role 'Viewer'

# provide a demo of how custom roles can be created and show the auth workaround for the API
