# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files # prevents giant files from being committed.
    -   id: check-json # checks json files for parseable syntax.
    -   id: check-yaml # checks yaml files for parseable syntax.
    -   id: check-merge-conflict # checks for files that contain merge conflict strings.
    -   id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source.
    -   id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
    -   id: requirements-txt-fixer # sorts entries in requirements.txt.
    -   id: trailing-whitespace # trims trailing whitespace.
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8 # enforces flake8 style consistency across Python projects.
        language_version: python3
        args: [--max-line-length=200] # override the max-line-length

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports # This hook reorders imports in python files.

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade # Automatically upgrade syntax for newer versions
        args: [--py36-plus]

-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.3.1
    hooks:
    -   id: sqlfluff-lint # Lints sql files with `SQLFluff`
        args: [--dialect, "snowflake"]
        additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']
