---
data_source snowflake_db:
    type: snowflake
    connection:
        username: ${SNOWFLAKE_USER}
        password: ${SNOWFLAKE_PASSWORD}
        account: ${SNOWFLAKE_ACCOUNT}
        database: ${SNOWFLAKE_DATABASE}
        warehouse: ${SNOWFLAKE_WAREHOUSE}
        role: ${SNOWFLAKE_ROLE}
        client_session_keep_alive: true
        session_parameters:
            QUERY_TAG: soda-queries
            QUOTED_IDENTIFIERS_IGNORE_CASE: false
        schema: ${DWH_WAREHOUSE}
