---
airflow_args:
  airflow_version: 2.2.0
  python_version: 3.9
  constraints_url: https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt
  airflow_home_dir: ~/airflow/
  admin_pass: ${sf_pass_dbt_demo}
  user_demo_pass: ${user_demo}
